# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', django_mysql.models.JSONField(default=dict, verbose_name={})),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('assignment', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
