# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='A', max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
